### ISSUE TITLE
Audio does not play in the background

### ISSUE THREAD

**Issue by MightyK1337** [theweavrs/BreadPlayer#63] opened 2016-12-03 03:37 UTC
1. When the navigation is away from the app like pressing the home button or back button
2. When lockscreen time out sets in and phone locks when playing the song.

Ideally, the song should continue playing in the above scenarios, but the song is getting paused, and we need to go to the player and press the play button to play the song again. This is different from the suggestion in #21 where if we go back to app, the song played automatically.

This is an important issue, since it is expected that a music player plays the song in the background, while we perform other things.

**Comment by theweavrs** [comment] 2016-12-03 05:14
@MightyK1337 This is strange, I just tested this last night and it was working without an issue. I will test again. Do tell me about auto-library loading and any other bugs you may find :)

**Comment by theweavrs** [comment] 2016-12-03 05:31
@MightyK1337 I can't reproduce this in the emulator. @DannyTalent Can you give this a go?

**Comment by DannyTalent** [comment] 2016-12-03 06:22
What happens is the music stops playing, but can be resumed manually via SMTC

**Comment by theweavrs** [comment] 2016-12-03 07:01
@DannyTalent I still can't get this to reproduce.

**Comment by DannyTalent** [comment] 2016-12-03 13:00
Hmmm well, it does happen every time you go anywhere else (outside the app)

**Comment by theweavrs** [comment] 2016-12-17 23:49
@DannyTalent Please confirm #64 and #63 are fixed.

**Comment by DannyTalent** [comment] 2017-01-11 17:42
Still happening on a1.1.0

**Comment by theweavrs** [comment] 2017-01-11 21:50
@DannyTalent I can reproduce this. Fixing.

**Comment by theweavrs** [comment] 2017-04-06 08:56
This should now be fixed in the latest builds.

**Closed by theweavrs** 2017-04-06 08:56 UTC
Labels: bug, windowsphone
