### ISSUE TITLE
Audio cuts and jumps on Mobile

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#39] opened 2016-11-16 02:31 UTC
(Optimization?) Lumia 735, experiencing audio cuts and sometimes quick jumps, frequently. The phone doesn't have many apps opened, no more than normal.

Happens both with the app on screen (happens just as much) and background

**Comment by theweavrs** [comment] 2016-11-16 03:12
How many songs did you load into the library?
Did you open the album view by chance?

**Comment by DannyTalent** [comment] 2016-11-16 03:58
**How many songs:** Around 607
**Did I open album view?: **Yes, but even when I "cold started" the app and only opened the library, it happens
**Size of song:** Happens on most/all songs. But one example is a 3:06, 7.22 MiB MP3 file
**Does it occur on other players? **Not on Groove, not on foobar2000

**Comment by theweavrs** [comment] 2016-11-16 04:09
Or perhaps there is some stream parsing problem. Can you send one file on which it was occurring for testing?

**Comment by DannyTalent** [comment] 2016-11-16 05:32
I don't think it's the audio file, because PC bread player can play it with no issue

Here's the [original file ](https://1drv.ms/u/s!Aj8wj2HQapfdopYzV_5K4-NBP6nXxw)(hosted on OneDrive not here bc copyright maybe)

[Here's that file played on Bread Player on Mobile](https://1drv.ms/u/s!Aj8wj2HQapfdopY2zmZnBMMgvOd5MQ)
[Here's that file played on Groove on Mobile](https://1drv.ms/u/s!Aj8wj2HQapfdopY1I0JSYIHu4880Rg)
(don't mind the peaks, that's just because of the crappy cable I used)
And another thing, it doesn't happen as much when connected to "headphones"

**Comment by MightyK1337** [comment] 2016-11-18 11:14
It happens for a lot of songs not just a particular one and even on headphones, at least for me.

**Comment by theweavrs** [comment] 2016-11-18 11:37
@DannyTalent  @MightyK1337  As it doesn't happen in the emulator, I have uploaded a test package
 with some changes for you guys to check out if this occurs again.

Here's the direct link: [Alpha-1.6.1-test](https://github.com/theweavrs/BreadPlayer/releases/download/v0.1.6.1-alpha/BreadPlayer.Core_0.1.6.0_arm.appxbundle)

_Basically, I removed SMTC as I suspect that is what's causing the issue. I could be wrong though._

**Comment by DannyTalent** [comment] 2016-11-18 16:01
True. I could reproduce it on the last alpha, but not on the new one
Also the bug reported by @MightyK1337 at #21 seems fixed

_Side note: The first time I tried to play a song, the app crashed_

**Comment by theweavrs** [comment] 2016-11-18 16:09
As I suspected! I will try a few things to fix this without removing SMTC.

**Comment by theweavrs** [comment] 2016-11-18 17:56
@DannyTalent Please test this one out: [Alpha-1.6.1-test-2](https://github.com/theweavrs/BreadPlayer/releases/download/v0.1.6.1-alpha/BreadPlayer.Core_0.1.6.1_arm.appxbundle)

_Side note: You may experience cuts and jumps in the background. Aside from that, SMTC will now be working flawlessly (I hope)._

**Comment by theweavrs** [comment] 2016-11-19 08:30
@DannyTalent Updates?

**Comment by DannyTalent** [comment] 2016-11-19 22:33
Crap, I forgot to check this issue, and my email, sorry!
Good to see some animations now! (or maybe I just noticed it now?)
SMTC works alright. Background audio stops itself when I "minimize" the app (eg. navigate to another app or press the Windows button) but can be played again manually, jumps and cuts are waaaaaaay less than before, but certainly still (rarely) present.

**Comment by theweavrs** [comment] 2016-11-20 04:53
Oh yes, I fixed that issue. 

About the cuts and jumps, I am glad that it occurs way less now but it still does so I will have to tweak some other things as well.

I have a question: In which state does it occur more? Background or foreground?

**Comment by DannyTalent** [comment] 2016-11-20 06:52
Definitely on the background. Playing a game (candy crush soda so it's ported, and a bit resource intensive) I noticed it happening, as well as while browsing on Edge.
Audio cuts only, tho... I've noticed they happen waaay less but are longer now (less than a second, but longer than before)

**Comment by theweavrs** [comment] 2016-11-30 19:12
@DannyTalent Is this still present in 1.7-alpha?

**Comment by DannyTalent** [comment] 2016-11-30 19:47
It does happen, not much, but it's quite inconsistent... Sometimes it will work with a few jumps for several minutes and sometimes the audio just gets fubar... But it's only happened to me once, when the phone was quite hot

**Comment by theweavrs** [comment] 2016-12-01 13:22
@DannyTalent I reproduced this on the emulator and it happens regardless of the SMTC. I think this issue is caused by high resource usage or low memory limit. Though, I wasn't able to get any message regarding low memory limit reached etc.

I think, on the background the app is given less memory and cpu because of which the audio stream buffering is slow, and audio cuts and jumps.

I will consult this with BASS devs, maybe they have something...

**Comment by DannyTalent** [comment] 2016-12-01 19:04
I think there's a task manager-esque app that shows you, though it needs some special access.. I'll report anything I can if I do find it

**Comment by theweavrs** [comment] 2016-12-01 19:19
@DannyTalent I did some of my own testing and it seems I am right. The OS puts a CPU limit on the player or maybe the BASS does that itself. Anyways, I saw > 2% usage of BASS on the foreground while on the background it was < 1%. So I am now sure where the problem is.

**Comment by theweavrs** [comment] 2016-12-03 05:15
@DannyTalent Please give this one a try again in the latest alpha. I am hoping this is fixed now...

**Comment by DannyTalent** [comment] 2016-12-03 06:27
Yep, mostly fixed. I did notice a small cut during a game's loading screen, so it may be a read speed issue?? I wouldn't know, but during the game it didn't happen again

**Comment by theweavrs** [comment] 2016-12-03 06:48
Can you give it a stress test? Like try loading heavy websites while song plays in background. Play some game (The ported Candy Crush 😉 ). I need to know if the config we have now will remain good under stressful conditions.

**Comment by DannyTalent** [comment] 2016-12-03 13:09
I tried the digrace of an app that they call Facebook Messenger, and didn't have any problems, again, a single jump while loading, but never again. I did however, found a bug I'll post about in a sec

**Closed** 2016-12-03 18:22 UTC
Labels: bug, windowsphone
