### ISSUE TITLE
songs not playing on windows 10 creators fall update insiders preview

### ISSUE THREAD

**Issue by touseefbsb** [theweavrs/BreadPlayer#148] opened 2017-05-29 18:32 UTC
### Actual Behaviour:
I am using windows 10 creators fall update as announced in build 2017, it is insiders preview build. I downloaded the latest version of bread player just now from the store to test it and it doesnt matter how I try to play the song it gets stuck at 0:01 seconds and doesn move further, all other features seem to work just fine

**Comment by theweavrs** [comment] 2017-05-29 18:44
Are the songs DRM protected? Did you get them by using Groove Music Pass?

**Comment by touseefbsb** [comment] 2017-05-29 19:03
no they are local music files, just normal mp3 files on my laptop

**Comment by theweavrs** [comment] 2017-05-29 19:06
Does the player hang? Do you hear any sound at all when the starts? Also, try loading some other songs and play them.

**Comment by touseefbsb** [comment] 2017-05-29 19:15
I tried to play them from within the player ( from loaded toasts ) then I tried to open file and play from the player and then I tried to right click my music files and open with break player. No the player doesnt hang, it adapts the color, album art,background, song name and everything according to that specific song. then the player movies to 0:01 and doesnt go further, and no I do not hear any sound even for that 1 second. I try to seek it further but it drops back to 0:01 the player shows pause button, which shows that song is supposed to be playing. and application remains normal and responsive everywhere and all other features work perfect apart from song playing.

**Comment by theweavrs** [comment] 2017-05-29 19:18
Strange behavior. Are you sure the songs are not broken or protected somehow? Try playing them in WMP or VLC or Groove.

**Comment by touseefbsb** [comment] 2017-05-29 19:23
Yes I am succesfully able to play them in other players, just checked again it works fine with groove

**Comment by touseefbsb** [comment] 2017-05-29 19:26
there is a possibiliy that problem is only on the insiders preview version of OS because I am running that, Even if I am able to debug the code on visual studio on my PC it wont give any hint because it is not causing any exception.

**Comment by theweavrs** [comment] 2017-05-29 19:27
Please upload the log file, perhaps there will some hint to what is happening. It will located in your Music Library folder under **.breadplayer** folder.

**Comment by touseefbsb** [comment] 2017-05-29 19:31
here is the log file

18:01:39:854|INFO | 2|XLog.LogManager|>>> LogManager initialized successfully. UTC time: Mon, 29 May 2017 13:01:39 GMT
18:01:40:372|INFO | 2|BLogger|App launched and session started...
18:01:40:070|INFO | 2|BLogger|Events initialized. Progressing in app constructor.
18:01:40:797|INFO | 2|BLogger|Content set to Window successfully...
18:01:40:797|INFO | 2|BLogger|Navigating to Shell...
18:01:46:417|INFO | 2|BLogger|App left background and is now in foreground...
18:01:46:707|ERROR| 2|BLogger|No songs were found!
18:03:01:713|ERROR| 2|BLogger|No songs were found!
18:04:59:582|INFO | 2|BLogger|App has entered background...
18:05:02:070|INFO | 2|BLogger|App suspended and session terminated. Session length: 3.36078496666667
18:05:02:110|INFO | 2|BLogger|Background Player ran for: 
18:05:02:476|INFO | 2|BLogger|state has been changed to stopped.
18:05:04:050|INFO | 2|BLogger|Logger initialized. Progressing in app constructor.
18:05:04:088|INFO | 2|BLogger|App launched and session started...
18:05:04:091|INFO | 2|BLogger|Content set to Window successfully...
18:05:04:518|INFO | 2|BLogger|App left background and is now in foreground...
18:09:45:021|INFO | 2|BLogger|state has been changed to stopped.
18:09:45:065|INFO | 2|BLogger|state has been changed to stopped.
18:10:14:590|INFO | 2|BLogger|state has been changed to stopped.
18:10:14:594|INFO | 2|BLogger|state has been changed to stopped.
18:10:20:856|INFO | 2|BLogger|state has been changed to paused.
18:10:52:584|INFO | 2|BLogger|state has been changed to stopped.
18:10:52:592|INFO | 2|BLogger|state has been changed to stopped.
18:11:30:320|INFO | 2|BLogger|App has entered background...
18:11:32:210|INFO | 2|BLogger|App suspended and session terminated. Session length: 6.46869258833333
18:11:32:456|INFO | 2|BLogger|state has been changed to stopped.
22:51:26:998|INFO | 2|BLogger|Content set to Window successfully...
22:51:27:660|INFO | 2|BLogger|App left background and is now in foreground...
22:51:26:999|INFO | 2|BLogger|Navigating to Shell...
22:56:27:242|INFO | 7|BLogger|Library successfully loaded!
22:57:18:808|INFO |13|BLogger|Songs successfully imported! Total Songs: 2013; Failed: 0; Loaded: 2015
22:59:15:592|INFO | 2|BLogger|state has been changed to stopped.
22:59:17:418|INFO | 2|BLogger|state has been changed to stopped.
22:59:21:850|INFO |12|BLogger|Songs successfully imported! Total Songs: 2013; Failed: 0; Loaded: 2015
23:00:05:094|INFO | 2|BLogger|App has entered background...
23:00:06:852|INFO | 2|BLogger|App suspended and session terminated. Session length: 8.66737344333333
23:00:07:043|INFO | 2|BLogger|Application is being suspended, disposing everything.
23:00:07:043|INFO | 2|BLogger|Background Player ran for: 
23:00:23:507|INFO | 2|BLogger|state has been changed to stopped.
23:01:14:768|INFO | 2|BLogger|Navigating to Shell...
23:01:15:134|INFO | 2|BLogger|Player opened successfully with file as argument...
23:01:15:134|INFO | 2|BLogger|App left background and is now in foreground...
23:01:15:827|INFO | 2|BLogger|state has been changed to stopped.
23:01:16:904|INFO | 2|BLogger|state has been changed to stopped.
23:01:23:757|INFO | 7|BLogger|Library successfully loaded!
23:03:01:807|INFO | 2|BLogger|state has been changed to stopped.
23:03:05:598|INFO | 2|BLogger|state has been changed to stopped.
23:03:11:336|INFO | 2|BLogger|state has been changed to stopped.
23:03:11:339|INFO | 2|BLogger|state has been changed to stopped.
23:03:17:357|INFO | 2|BLogger|state has been changed to stopped.
23:03:24:479|INFO | 2|BLogger|App has entered background...
23:03:26:860|FATAL| 2|BLogger|Something caused the app to crash! --> System.NullReferenceException: Arg_NullReferenceException
   at BreadPlayer!<BaseAddress>+0xef6b5d
   at SharedLibrary!<BaseAddress>+0x69993e
   at SharedLibrary!<BaseAddress>+0x497d7c
00:24:20:198|INFO | 2|BLogger|Content set to Window successfully...
00:24:20:895|INFO | 2|BLogger|Player opened successfully with file as argument...
00:24:22:265|INFO | 2|BLogger|state has been changed to stopped.
00:24:25:152|INFO | 2|BLogger|state has been changed to stopped.
00:24:31:313|INFO |12|BLogger|Library successfully loaded!
00:24:35:336|INFO | 2|BLogger|state has been changed to paused.
00:24:53:901|INFO | 2|BLogger|App has entered background...

**Comment by great-ssh** [comment] 2017-07-04 15:35
Hello touseefbsb;
thank you for your report.
there is a little problem on windows creators update (1703) that makes groove and other music players related to it to corrupt.
fortunately we are working on it.
please be patient.
thank you.

**Comment by theweavrs** [comment] 2017-07-26 22:46
closing due to inactivity and this bug is also not reproducible.

**Comment by touseefbsb** [comment] 2017-08-03 17:52
just wanted to remind you that I tried it again and problem is still the same, I hope it gets fixed soon :) Thanks

**Comment by theweavrs** [comment] 2017-08-03 18:34
I do not have Fall Creators Update so cannot test this or reproduce this. Anyhow, I will keep this open as there might be a bug. Thanks for contributing.

**Comment by theweavrs** [comment] 2017-10-18 17:45
Tested on Fall Creators Update RTM and cannot reproduce. Closing. Please reopen if you are still having these issues.

**Closed by theweavrs** 2017-10-18 17:45 UTC
