### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by borna761** [theweavrs/BreadPlayer#97] opened 2017-01-25 15:57 UTC
Faulting application name: BreadPlayer.exe, version: 1.0.0.0, time stamp: 0x58782e55
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.15014.1000, time stamp: 0x8b3c08fe
Exception code: 0xc000027b
Fault offset: 0x000000000077a3ba
Faulting process id: 0x3758
Faulting application start time: 0x01d2771afcf4cd81
Faulting application path: C:\Program Files\WindowsApps\22102thecodrr.BreadPlayer_1.1.0.0_x64__fknyqnmcp2942\BreadPlayer.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: f88a6dcc-89d4-49d9-b86b-7add99a65edf
Faulting package full name: 22102thecodrr.BreadPlayer_1.1.0.0_x64__fknyqnmcp2942
Faulting package-relative application ID: App

**Comment by theweavrs** [comment] 2017-01-25 17:42
Where does this exception occur and are you building from source?

**Comment by borna761** [comment] 2017-01-25 18:55
Happened randomly just while playing music. App is installed from store.

**Comment by borna761** [comment] 2017-01-27 22:13
Not sure if any of this helps:

Fault bucket 133454638297, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: 22102thecodrr.BreadPlayer_1.1.0.0_x64__fknyqnmcp2942
P2: praid:App
P3: 1.0.0.0
P4: 58782e55
P5: StackHash12_043
P6: 0.0.0.0
P7: 00000000
P8: 88000fa8
P9: 0
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8000.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER808E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER808D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER80AD.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_22102thecodrr.Br_1eb439e82abd562e546998956e888d4539bd3a14_f78a9966_17de8465

Analysis symbol: 
Rechecking for solution: 0
Report Id: 59166cf1-d913-491d-85b1-08a4759a8eb6
Report Status: 268435456
Hashed bucket: caeca6550255fad9479dbef27216b173
[Report.zip](https://github.com/theweavrs/BreadPlayer/files/736383/Report.zip)

**Comment by theweavrs** [comment] 2017-01-28 09:02
Can't pinpoint the exception to the specific code line or block. I will release a new version in the coming days, perhaps this is already fixed. :)

Thank you so much for reporting. :)

**Comment by borna761** [comment] 2017-01-30 15:44
Adding another one just in case it helps.
[Report.zip](https://github.com/theweavrs/BreadPlayer/files/739392/Report.zip)

**Comment by theweavrs** [comment] 2017-02-09 00:04
@borna761 A new version of Bread Player is released! Please check it out and tell if this bug is fixed!

Get it from [here](https://www.microsoft.com/en-us/store/p/bread-player/9nblggh42srx)!

**Comment by borna761** [comment] 2017-02-15 22:38
Happened again:

Faulting application name: BreadPlayer.exe, version: 1.0.0.0, time stamp: 0x589597a4
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.15031.0, time stamp: 0x29e0f779
Exception code: 0xc000027b
Fault offset: 0x000000000043103f
Faulting process id: 0x390c
Faulting application start time: 0x01d287ca6a9fe5b5
Faulting application path: C:\Program Files\WindowsApps\22102thecodrr.BreadPlayer_1.2.1.0_x64__fknyqnmcp2942\BreadPlayer.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 675d6e93-ebe8-46d2-b745-d47a62ca1958
Faulting package full name: 22102thecodrr.BreadPlayer_1.2.1.0_x64__fknyqnmcp2942
Faulting package-relative application ID: App

**Comment by theweavrs** [comment] 2017-02-16 00:16
@borna761 Okay, I see the problem is still there. Tell me exactly what you did, I mean exactly as in hover over a list item? Or perhaps some other control? Or did you changed a song? Things like that. This is a problem with some XAML failing or some such so it would help if you could pinpoint exactly where and how it happened even if it was some random action. Thanks a lot for reporting again :)

**Comment by borna761** [comment] 2017-02-16 18:57
@theweavrs It happens intermittently when playing music. I'm just leaving it open in the background and then it closes down. I've noticed it seems to be more frequently when it switches between songs, so that might have something to do with it.
I wish I could give a more detailed report than that, sorry!

**Comment by borna761** [comment] 2017-02-19 17:20
More crash:

Faulting application name: BreadPlayer.exe, version: 1.0.0.0, time stamp: 0x589597a4
Faulting module name: twinapi.appcore.dll, version: 10.0.15031.0, time stamp: 0x31aa4e20
Exception code: 0xc000027b
Fault offset: 0x0000000000033d3a
Faulting process id: 0x1f10
Faulting application start time: 0x01d28ad38da8ce5e
Faulting application path: C:\Program Files\WindowsApps\22102thecodrr.BreadPlayer_1.2.1.0_x64__fknyqnmcp2942\BreadPlayer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
Report Id: b224c756-8ef2-4ed3-8cd8-046d48eaaa3c
Faulting package full name: 22102thecodrr.BreadPlayer_1.2.1.0_x64__fknyqnmcp2942
Faulting package-relative application ID: App

I open up the player, play a song, and at the end of the song it crashes. I can then open again, play the next song, after which it crashes. And repeat.

**Comment by theweavrs** [comment] 2017-04-02 13:37
@borna761 Please confirm this bug in the nightly builds.

**Comment by theweavrs** [comment] 2017-04-06 08:48
I am closing this for now as it is not reproducible anywhere and is a unique issue never reported elsewhere.

**Closed by theweavrs** 2017-04-06 08:48 UTC
Labels: bug, investigating
