### ISSUE TITLE
"0 songs" album, also crashing the app

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#15] opened 2016-10-25 16:18 UTC
I have a song I ripped from YouTube, and did the ID3 myself. The player shows the album name, artist name, but shows 0 songs · 0.0 Minutes. When I try to play it, the application crashes.

It probably has to do with the handling of foreign characters, the filename is "∆$†ɌῗØ - CɌY$†∆Ɫ ШЄЄD (ØЯỊ₲ỊИ∆Ɫ MỊX).mp3"

**What it does: **Application crashes
**What it should do: **Throw error, or play the song

PC and Mobile

**Comment by theweavrs** [comment] 2016-10-25 16:42
That's odd. I will rename an mp3 file and try to reproduce. Let's see what happens.

Can Groove Play it?

**Comment by DannyTalent** [comment] 2016-10-25 16:49
Yep Groove can play it normally.
Also, there are no foreign characters on the metadata

**Comment by theweavrs** [comment] 2016-10-25 17:01
You mean when you click the play button on album thumbnail, then the app crashes? 

Try and click on the album art, this will open the album view with all the songs in the album. Try playing the song from there.

**Comment by DannyTalent** [comment] 2016-10-25 17:08
Yeah, that crashes it.

Once again, opening the album art shows "0 songs · 0.0 Minutes", and shows nothing else.
When I click on Play All, it also causes a crash

**Comment by theweavrs** [comment] 2016-10-25 17:10
Yes, I think I understand where the problem is. Thanks.

**Comment by theweavrs** [comment] 2016-10-25 17:55
The problem wasn't in the filename or the illegal characters, it was because of empty album. Now fixed.

**Closed** 2016-10-26 16:02 UTC
Labels: bug, windows, windowsphone
